---
title: "ICPSR/Retraction Watch, First Look"
author: "Ashvin Narayan"
date: "26 September 2025"
output: pdf_document
---

```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(ggplot2)
library(lubridate)

sys.source("Preprocessing.R", envir = knitr::knit_global())
```

### DOIs available?

```{r dois-1}
# What proportion of entries in each table have DOIs (ICPSR, Retraction Watch)
c(length(icpsr$DOI[which(!is.na(icpsr$DOI))]) / length(icpsr$DOI),
  length(retractions$OriginalPaperDOI[which(!is.na(retractions$OriginalPaperDOI))]) /
    length(retractions$OriginalPaperDOI))

# Duplicate DOIs in retractions?
retractions |> 
  drop_na(OriginalPaperDOI) |>
  add_count(OriginalPaperDOI) |> 
  filter(n > 1) |>
  distinct() |>
  select("Record.ID", "Title", "OriginalPaperDOI", "n") |>
  nrow()

# Retraction Watch database contains 'duplicate' DOIs - if a paper 
# was corrected then retracted, there are separate entries for the 
# correction and the retraction

# pivot_wider before merging?

# How many entries for each type of retraction reason?
retractions |>
  drop_na(RetractionNature) |>
  group_by(RetractionNature) |>
  summarize(n())
```

```{r dois-2}
# Duplicate DOIs in ICPSR?

icpsr |> 
  drop_na(DOI) |>
  add_count(DOI) |> 
  filter(n > 1) |>
  distinct() |>
  select("Reference.ID", "Title", "DOI", "n") |>
  nrow()

# Doesn't look like it! Thank you data librarians :)
```

\newpage

### RIS Types

```{r icpsr-ris-type}
# Article type found in 'RIS.Type' column, not 'Article.Type'

# For entries without DOIs in ICPSR, what type of materials are they?

# 'RIS.Type' available for what proportion of icpsr entries?
icpsr |>
  drop_na(RIS.Type) |>
  select("Reference.ID", "Title", "DOI", "RIS.Type") |>
  nrow() / nrow(icpsr)

# 'RIS.Type' available for what proportion of icpsr entries
# that have a DOI?
icpsr |>
  drop_na(DOI) |>
  drop_na(RIS.Type) |>
  select("Reference.ID", "DOI", "Type.of.Work") |>
  nrow() / nrow(filter(icpsr, is.na(DOI)))

# ... that don't have a DOI?
icpsr |>
  filter(is.na(DOI)) |>
  drop_na(RIS.Type) |>
  select("Reference.ID", "Title", "DOI", "Type.of.Work") |>
  nrow() / nrow(filter(icpsr, is.na(DOI)))

# 'Type.of.Work' appears to be available for < 10% of entries - 
# around 5.4% of entries with a DOI and 18.5% of those w/o a DOI

# TODO: fix NA values - diff NA values associated w diff columns

# How many entries associated with each type of work?
icpsr |>
  drop_na(RIS.Type) |>
  filter(RIS.Type != "(unknown)") |>
  group_by(RIS.Type) |>
  summarize(count = n()) |>
  arrange(desc(count))

# Needs to be standardized .. capitalization differences interfering
```

```{r rw-article-types}
# 'ArticleType' unavailable for what proportion of RW entries?
retractions |>
  select(Record.ID, ArticleType) |>
  drop_na(ArticleType) |>
  nrow()

# ArticleType available for all RW entries, it looks like!

# How many entries associated with each type of work in RW?
retractions |>
  select(Record.ID, ArticleType) |>
  drop_na(ArticleType) |>
  unnest(c(ArticleType)) |>
  group_by(ArticleType) |>
  summarize(count = n()) |>
  arrange(desc(count))

# These overlap - ArticleType is a list-type column
```

\newpage

### Publishers

```{r publishers}
# Publication name available for what proportion of entries?

# Secondary.Title includes publication name if entry is 
# a journal/newspaper
icpsr |>
  select(Reference.ID, Secondary.Title) |>
  drop_na(Secondary.Title) |>
  nrow() / nrow(icpsr)

# Now looking at Publisher - contains info on gov't
# bureaus etc responsible for the publication
# Approx equivalent to 'Institution' in RW data?
icpsr |>
  select(Reference.ID, Publisher) |>
  drop_na(Publisher) |>
  nrow() / nrow(icpsr)

# Around 36% of icpsr entries list the publisher

# What about those entries without DOI?

# Secondary.Title
icpsr |> 
  filter(is.na(DOI)) |>
  select(Reference.ID, Secondary.Title) |>
  drop_na(Secondary.Title) |>
  nrow() / nrow(filter(icpsr, is.na(DOI)))

# Publisher
icpsr |> 
  filter(is.na(DOI)) |>
  select(Reference.ID, Publisher) |>
  drop_na(Publisher) |>
  nrow() / nrow(filter(icpsr, is.na(DOI)))

# Around 64% of entries without a DOI have a publisher listed

# What publications appear frequently in ISPCR?

# Secondary.Title
icpsr |> 
  select(Reference.ID, Secondary.Title) |>
  drop_na(Secondary.Title) |>
  group_by(Secondary.Title) |>
  summarize(count = n()) |>
  arrange(desc(count))

# Publisher
icpsr |> 
  select(Reference.ID, Publisher) |>
  drop_na(Publisher) |>
  group_by(Publisher) |>
  summarize(count = n()) |>
  arrange(desc(count))
```

```{r publishers-2}
# Publication name available for what proportion of entries in RW?

# Secondary.Title includes publication name if entry is 
# a journal/newspaper
retractions |>
  select(Record.ID, Journal) |>
  drop_na(Journal) |>
  nrow() / nrow(retractions)

# All entries list a 'Journal' - column just holds the source
# of the article (incl. journals, books, serials, etc)

# What journals are most common in RW?

retractions |> 
  select(Record.ID, Journal) |>
  drop_na(Journal) |>
  unnest(c(Journal)) |>
  group_by(Journal) |>
  summarize(count = n()) |>
  arrange(desc(count))
```

### Merging

```{r merging}
# Initial brief attempt at a merge

merged <- inner_join(
  x = (icpsr %>% 
         filter(!is.na(DOI)) %>% 
         select(Reference.ID, Title, DOI) %>% 
         unnest(c(DOI))),
  y = (retractions %>% 
         filter(!is.na(OriginalPaperDOI)) %>% 
         select(Record.ID, Title, OriginalPaperDOI, RetractionDate, RetractionNature, Reason) %>% 
         unnest(c(OriginalPaperDOI))),
  by = join_by(DOI == OriginalPaperDOI)
)

print(merged)

# Is 9 observations around what we'd expect??
# Slightly concerning might be a data cleaning problem

# remove duplicate row from merged
merged = merged[c(1:4, 6:9),]
```

\newpage

## Citation Data

Change date strings to lubridate Date type
```{r handle-dates}
make_date = function(str) {
  # month, day, year format
  # day may or may not be included
  date_strs = unlist(strsplit(str, " "))
  
  # account for date ranges
  # TEMP - if a range is given, take the earliest given date
  if (str_length(date_strs[1]) > 3) {
    date_strs[1] <- strsplit(date_strs[1], "-")[[1]][1]
  } 
  if (str_length(date_strs[length(date_strs)]) > 4) {
    date_strs[length(date_strs)] <- 
      strsplit(date_strs[length(date_strs)], "-")[[1]][1]
  }
  if(length(date_strs) > 2 & str_length(date_strs[2]) > 2) {
    date_strs[2] <- strsplit(date_strs[2], "-")[[1]][1]
  }
  
  # QUESTION: What to do if day of publication is not provided?
  date_nums = c(
    # year
    as.character(date_strs[length(date_strs)]),
    # month
    as.character(which(date_strs[1] == str_to_upper(month.abb))),
    # day
    # TEMP FIX - use the first of the month if no day provided
    ifelse(length(date_strs) > 2, as.character(date_strs[2]), "1")
  )
  
  return(ymd(paste0(date_nums[1], "-", date_nums[2], "-", date_nums[3])))
}
```

```{r import-tables}
# read data - drop leading 10 rows
# drop citations by year data - will reconstru
process.tbl <- function(filename) {
  df <- read.csv(filename, skip = 10)
  df <- subset(df, select = c(1:21))
  df |> group_by(Publication.Year) |>
    summarise(Num.Citations = n()) -> cit_per_year
  return(cit_per_year)
}

# order corresponds to order of rows in merged
tblnames = c("citation-reports/WorldsApart.csv",
             "citation-reports/NonmetroRole.csv",
             "citation-reports/SchoolSocialBonds.csv",
             "citation-reports/SuicideNatDisasters.csv",
             "citation-reports/ECigUse.csv", 
             "citation-reports/HowDidTheyDecide.csv",
             "citation-reports/MarijuanaUse.csv",
             "citation-reports/TurningIn.csv"
             )
```


```{r citation-data, tidy = TRUE, tidy.opts = list(width.cutoff = 80)}

# set console width
options(width = 80)

get.proportions = function(filename) {
  # load in table
  tbl = process.tbl(filename)
  
  # get retraction year
  ix = which(tblnames == filename)
  mdy_hm(merged$RetractionDate[[ix]]) |> 
    year() -> ret_year
  
  # number of citations pre- and post- retraction
  # excludes citations from the same year - more work needed to try to use
  # day/month for comparison
  pre_ret = (sum(tbl$Num.Citations[which(tbl$Publication.Year < ret_year)]) / 
               sum(tbl$Num.Citations))
  post_ret = (sum(tbl$Num.Citations[which(tbl$Publication.Year > ret_year)]) / 
                sum(tbl$Num.Citations))
  
  return(c(pre_ret, post_ret))
}

# plot citations over time
plot.citations = function(filename) {
  tbl = process.tbl(filename)
  mdy_hm(merged$RetractionDate[[ix]]) |> 
    year() -> ret_year
  
  # get xlim for plot - make sure retraction
  # year is included
  min_x = min(
    ret_year,
    min(tbl$Publication.Year)
  )
  max_x = max(
    ret_year,
    max(tbl$Publication.Year)
  )
  
  plot(x = process.tbl(tblnames[ix])$Publication.Year,
       y = process.tbl(tblnames[ix])$Num.Citations,
       type = 'o', pch = 20,
       main = strwrap(paste0("Citations of ", '\"',
                             merged$Title.x[ix], '\"'),
                      width = 50),
       xlab = "Publication Year",
       ylab = "Number of Citations",
       xlim = c(min_x, max_x)
      )
  abline(v = mdy_hm(merged$RetractionDate[[ix]]) %>% year(), 
         lwd = 2, col = "red")
  
  cplot = recordPlot()
    
  return(cplot)
}

# setwd(...)

for (ix in 1:length(merged)) {
  # print proportion of citations from before, 
  # after retraction year
  prop_citations = get.proportions(tblnames[ix])
  print(strwrap(merged$Title.x[ix], width = getOption("width")))
  cat("Pre-retraction:", prop_citations[1],
      ", Post-retraction", prop_citations[2], "\n",
      fill = FALSE)
  
  # plot citations
  print(plot.citations(tblnames[ix]))
}
```








